PROC SQL;

	TITLE "DEFAULT RATES OF TRAINING SAMPLE (TOTAL) - 70:30";
	SELECT
		COUNT(*) AS NR
		,SUM(DEFAULT_12M) AS NR_DEF
		,AVG(DEFAULT_12M) AS DR FORMAT PERCENT18.6
	FROM final.&USED_DATASET._FINAL
	WHERE SELECTED_70_30 = 1;

	TITLE "DEFAULT RATES OF TEST SAMPLE (TOTAL) - 70:30";
	SELECT
		COUNT(*) AS NR
		,SUM(DEFAULT_12M) AS NR_DEF
		,AVG(DEFAULT_12M) AS DR FORMAT PERCENT18.6
	FROM final.&USED_DATASET._FINAL
	WHERE SELECTED_70_30 = 0;

	TITLE "DEFAULT RATES OF TRAINING/TEST SAMPLE - 70:30";
	SELECT 
		a.DATUM
		,a.NR AS NR_TRAIN
		,b.NR AS NR_TEST
		,a.NR_DEF AS NR_DEF_TRAIN
		,b.NR_DEF AS NR_DEF_TEST
		,a.DR AS DR_TRAIN FORMAT PERCENT18.6
		,b.DR AS DR_TEST FORMAT PERCENT18.6
	FROM 
		(
			SELECT
				DATUM
				,COUNT(*) AS NR
				,SUM(DEFAULT_12M) AS NR_DEF
				,AVG(DEFAULT_12M) AS DR
			FROM final.&USED_DATASET._FINAL
			WHERE SELECTED_70_30 = 1
			GROUP BY DATUM
		) a 
	LEFT JOIN 
		(
			SELECT
				DATUM
				,COUNT(*) AS NR
				,SUM(DEFAULT_12M) AS NR_DEF
				,AVG(DEFAULT_12M) AS DR
			FROM final.&USED_DATASET._FINAL
			WHERE SELECTED_70_30 = 0
			GROUP BY DATUM
		) b
	ON a.DATUM = b.DATUM;

	TITLE;
QUIT;

PROC SQL;

	TITLE "DEFAULT RATES OF TRAINING SAMPLE (TOTAL) - 50:50";
	SELECT
		COUNT(*) AS NR
		,SUM(DEFAULT_12M) AS NR_DEF
		,AVG(DEFAULT_12M) AS DR FORMAT PERCENT18.6
	FROM final.&USED_DATASET._FINAL
	WHERE SELECTED_50_50 = 1;

	TITLE "DEFAULT RATES OF TEST SAMPLE (TOTAL) - 50:50";
	SELECT
		COUNT(*) AS NR
		,SUM(DEFAULT_12M) AS NR_DEF
		,AVG(DEFAULT_12M) AS DR FORMAT PERCENT18.6
	FROM final.&USED_DATASET._FINAL
	WHERE SELECTED_50_50 = 0;

	TITLE "DEFAULT RATES OF TRAINING/TEST SAMPLE - 50:50";
	SELECT 
		a.DATUM
		,a.NR AS NR_TRAIN
		,b.NR AS NR_TEST
		,a.NR_DEF AS NR_DEF_TRAIN
		,b.NR_DEF AS NR_DEF_TEST
		,a.DR AS DR_TRAIN FORMAT PERCENT18.6
		,b.DR AS DR_TEST FORMAT PERCENT18.6
	FROM 
		(
			SELECT
				DATUM
				,COUNT(*) AS NR
				,SUM(DEFAULT_12M) AS NR_DEF
				,AVG(DEFAULT_12M) AS DR
			FROM final.&USED_DATASET._FINAL
			WHERE SELECTED_50_50 = 1
			GROUP BY DATUM
		) a 
	LEFT JOIN 
		(
			SELECT
				DATUM
				,COUNT(*) AS NR
				,SUM(DEFAULT_12M) AS NR_DEF
				,AVG(DEFAULT_12M) AS DR
			FROM final.&USED_DATASET._FINAL
			WHERE SELECTED_50_50 = 0
			GROUP BY DATUM
		) b
	ON a.DATUM = b.DATUM;

	TITLE;
QUIT;


PROC SQL;

	TITLE "DEFAULT RATES OF TRAINING SAMPLE (TOTAL) - 90:10";
	SELECT
		COUNT(*) AS NR
		,SUM(DEFAULT_12M) AS NR_DEF
		,AVG(DEFAULT_12M) AS DR FORMAT PERCENT18.6
	FROM final.&USED_DATASET._FINAL
	WHERE SELECTED_90_10 = 1;

	TITLE "DEFAULT RATES OF TEST SAMPLE (TOTAL) - 90:10";
	SELECT
		COUNT(*) AS NR
		,SUM(DEFAULT_12M) AS NR_DEF
		,AVG(DEFAULT_12M) AS DR FORMAT PERCENT18.6
	FROM final.&USED_DATASET._FINAL
	WHERE SELECTED_90_10 = 0;

	TITLE "DEFAULT RATES OF TRAINING/TEST SAMPLE - 90:10";
	SELECT 
		a.DATUM
		,a.NR AS NR_TRAIN
		,b.NR AS NR_TEST
		,a.NR_DEF AS NR_DEF_TRAIN
		,b.NR_DEF AS NR_DEF_TEST
		,a.DR AS DR_TRAIN FORMAT PERCENT18.6
		,b.DR AS DR_TEST FORMAT PERCENT18.6
	FROM 
		(
			SELECT
				DATUM
				,COUNT(*) AS NR
				,SUM(DEFAULT_12M) AS NR_DEF
				,AVG(DEFAULT_12M) AS DR
			FROM final.&USED_DATASET._FINAL
			WHERE SELECTED_90_10 = 1
			GROUP BY DATUM
		) a 
	LEFT JOIN 
		(
			SELECT
				DATUM
				,COUNT(*) AS NR
				,SUM(DEFAULT_12M) AS NR_DEF
				,AVG(DEFAULT_12M) AS DR
			FROM final.&USED_DATASET._FINAL
			WHERE SELECTED_90_10 = 0
			GROUP BY DATUM
		) b
	ON a.DATUM = b.DATUM;

	TITLE;
QUIT;

