PROC SQL;

	TITLE "DEFAULT RATES OF VALIDATION SAMPLE (TOTAL)";
	SELECT
		COUNT(*) AS NR
		,SUM(DEFAULT_12M) AS NR_DEF
		,AVG(DEFAULT_12M) AS DR FORMAT PERCENT18.6
	FROM final.OOT_SAMPLE_1Y;

	TITLE "DEFAULT RATES OF TEST SAMPLE (TOTAL) - 70:30";
	SELECT
		COUNT(*) AS NR
		,SUM(DEFAULT_12M) AS NR_DEF
		,AVG(DEFAULT_12M) AS DR FORMAT PERCENT18.6
	FROM final.OOT_SAMPLE_1Y;

	TITLE "DEFAULT RATES OF TRAINING/TEST SAMPLE";
	SELECT 
		DATUM
		,COUNT(*) AS NR_TOTAL
		,SUM(DEFAULT_12M) AS NR_DEF
		,AVG(DEFAULT_12M) AS DR FORMAT PERCENT18.6
	FROM final.OOT_SAMPLE_1Y a
	GROUP BY DATUM;

	TITLE;
QUIT;