ODS GRAPHICS / IMAGENAME="OOF_SAMPLE_MODEL_ROC" IMAGEFMT=PNG WIDTH = 20CM HEIGHT = 15CM;

PROC LOGISTIC DATA=OOF_SAMPLE;
	MODEL DEFAULT_12M(EVENT='1') = PD_LOG / OUTROC=VROC;
	ROC;
    ODS OUTPUT ROCASSOCIATION = TEMP2;
RUN;

DATA TEMP2;
SET TEMP2;
*WHERE ROCMODEL = 'Model';
	GINI = 2 * AREA - 1;

	LENGTH VARIABLE $ 50;
	VARIABLE = "PD";

	RENAME Area = AUC;
	DROP ROCModel;

RUN;