
/* STATISTICS FOR NUMERIC VARIABLES */
ODS SELECT NONE;
PROC MEANS DATA=&USED_DATASET. StackODSOutput N NMISS SUM MEAN MODE STD MIN P1 P5 P25 MEDIAN P75 P95 P99 MAX; 
VAR &NUM_VAR.;
CLASS GROUP2;
ODS OUTPUT summary=LongPctls_GROUP;
RUN;

PROC MEANS DATA=&USED_DATASET. StackODSOutput N NMISS SUM MEAN MODE STD MIN P1 P5 P25 MEDIAN P75 P95 P99 MAX; 
VAR &NUM_VAR.;
ODS OUTPUT summary=LongPctls;
RUN;
ODS SELECT ALL;

DATA LongPctls;
RETAIN GROUP;
SET LongPctls_GROUP LongPctls ;

GROUP = STRIP(PUT(GROUP2,8.));
IF GROUP = . THEN GROUP = 'ALL';

FORMAT MISS_PERCENTAGE PERCENT7.2;
MISS_PERCENTAGE = NMISS/(NMISS+N);

DROP NObs _control_ GROUP2;

RUN;

DATA &USED_DATASET._FINAL;
SET &USED_DATASET.;
RUN;

PROC SORT DATA=LongPctls OUT=LongPctls;
BY Variable GROUP;
RUN;

PROC SQL; DROP TABLE LongPctls_GROUP; QUIT;


/* CALCULATION OF OUTLIER PROPORTION AND OUTLIER TREATMENT OF NUMERIC VARIABLES */

%MACRO OUTLIER_PERC(DATA, VAR);

PROC SQL NOPRINT;

	SELECT COUNT(*) 		INTO :TOTAL_PERC TRIMMED FROM VARIABLELIST WHERE TYPE = "NUM";
	SELECT VARIABLE 		INTO :VAR1-:VAR&TOTAL_PERC. FROM VARIABLELIST WHERE TYPE = "NUM";
	SELECT FLAG_LOW_CAP 	INTO :FLAG_LOW_CAP1-:FLAG_LOW_CAP&TOTAL_PERC. FROM VARIABLELIST WHERE TYPE = "NUM";
	SELECT FLAG_HIGH_CAP 	INTO :FLAG_HIGH_CAP1-:FLAG_HIGH_CAP&TOTAL_PERC. FROM VARIABLELIST WHERE TYPE = "NUM";
	SELECT FLAG_MISSING 	INTO :FLAG_MISSING1-:FLAG_MISSING&TOTAL_PERC. FROM VARIABLELIST WHERE TYPE = "NUM";

QUIT;

	%DO O = 1 %TO &TOTAL_PERC.;
	%PUT ------------ &O. OF &TOTAL_PERC.: &&VAR&O.;

			PROC UNIVARIATE DATA=&DATA. NOPRINT;
			  VAR &&VAR&O.;
			  OUTPUT PCTLPRE=P_ PCTLPTS= 25, 50, 75 OUT=P25_P50_P75;
			RUN;

			PROC SQL NOPRINT; SELECT P_25, P_50, P_75 INTO :P25, :P50, :P75 FROM P25_P50_P75; QUIT;

			PROC SQL;
				CREATE TABLE TEMP AS
					SELECT 
						"&&VAR&O." AS VARIABLE
						, &P25.-(&P75.-&P25.)*1.5 AS L_BOARDER
						, &P75.+(&P75.-&P25.)*1.5 AS H_BOARDER
						, SUM(LOWER) AS L_OUTLIER
						, SUM(HIGHER) AS H_OUTLIER
						, SUM(LOWER)+SUM(HIGHER) AS OUTLIER
						, SUM(LOWER)/COUNT(LOWER) AS L_OUTLIER_PERC FORMAT PERCENT9.4
						, SUM(HIGHER)/COUNT(HIGHER) AS H_OUTLIER_PERC FORMAT PERCENT9.4
						, (SUM(LOWER)+SUM(HIGHER))/COUNT(LOWER) AS OUTLIER_PERC FORMAT PERCENT9.4
					FROM	(
						SELECT
							CASE WHEN &&VAR&O. < &P25.-(&P75.-&P25.)*1.5 THEN 1 ELSE 0 END AS LOWER
							, CASE WHEN &&VAR&O. > &P75.+(&P75.-&P25.)*1.5 THEN 1 ELSE 0 END AS HIGHER
						FROM &USED_DATASET.
							) hl;
			QUIT;

			DATA OUTLIER_PERC;
			SET OUTLIER_PERC TEMP;
				IF VARIABLE = '' THEN DELETE;
			RUN;

		%IF &&FLAG_LOW_CAP&O. = 1 OR &&FLAG_HIGH_CAP&O. = 1 OR &&FLAG_MISSING&O. = 1 %THEN %DO;

			DATA &USED_DATASET._FINAL;
			SET &USED_DATASET._FINAL;

				&&VAR&O.._ADJ = &&VAR&O.;

				%IF &&FLAG_MISSING&O. = 1 %THEN %DO;
					IF &&VAR&O.._ADJ = . THEN &&VAR&O.._ADJ = &P50.;
				%END;
				%IF &&FLAG_LOW_CAP&O. = 1 %THEN %DO;
					IF &&VAR&O. < &P25.-(&P75.-&P25.)*1.5 THEN &&VAR&O.._ADJ = &P25.-(&P75.-&P25.)*1.5;
				%END;
				%IF &&FLAG_HIGH_CAP&O. = 1 %THEN %DO;
					IF &&VAR&O. > &P25.+(&P75.-&P25.)*1.5 THEN &&VAR&O.._ADJ = &P25.+(&P75.-&P25.)*1.5;
				%END;
				%IF &&FLAG_MISSING&O. = 1 %THEN %DO;
					IF &&VAR&O.. = . THEN &&VAR&O.. = &P50.;
				%END;
	
			RUN;

		%END;

			PROC SQL; DROP TABLE TEMP, P25_P75; QUIT;

%END;

%MEND;

DATA OUTLIER_PERC;
LENGTH VARIABLE $ 50;
RUN;

%OUTLIER_PERC(DATA=&USED_DATASET.);

DATA &USED_DATASET._FINAL;
SET &USED_DATASET._FINAL;

	/* MISSING TREAMENT FOR IND VARIABLE, WHERE MISSING < 20% */
	flag_fthb_ADJ = flag_fthb;
	IF flag_fthb_ADJ = . THEN flag_fthb_ADJ = 1;

	IF flag_fthb = . THEN flag_fthb = 1;

	flag_mi_ADJ = flag_mi;
	IF flag_mi_ADJ = . THEN flag_mi_ADJ = 1;

	IF flag_mi = . THEN flag_mi = 1;
RUN;



/* RE-CALCULATE GINI AFTER MISSING AND OUTLIER TREATMENT */

ODS GRAPHICS ON / MAXOBS=10929045;
ODS LISTING GPATH='C:\Users\meikee.pagsinohin\Documents\MA\plot' IMAGE_DPI = 300 STYLE=JOURNAL;
ODS GRAPHICS / IMAGENAME="image" RESET=INDEX IMAGEFMT=PNG WIDTH = 20CM HEIGHT = 15CM ;

DATA GINI_KS_CORR_FIN;
LENGTH GROUP $ 5 VARIABLE $ 50 LABEL $ 150;
RUN;

%UNIV_ANALYSIS(DATA=&USED_DATASET._FINAL, VAR=fico_ADJ, GROUP=GROUP1, N_BAR=10, TYPE_VAR=NUM);
%UNIV_ANALYSIS(DATA=&USED_DATASET._FINAL, VAR=cltv_ADJ, GROUP=GROUP1, N_BAR=10, TYPE_VAR=NUM);
%UNIV_ANALYSIS(DATA=&USED_DATASET._FINAL, VAR=dti_ADJ, GROUP=GROUP1, N_BAR=10, TYPE_VAR=NUM);
%UNIV_ANALYSIS(DATA=&USED_DATASET._FINAL, VAR=ltv_ADJ, GROUP=GROUP1, N_BAR=10, TYPE_VAR=NUM);
%UNIV_ANALYSIS(DATA=&USED_DATASET._FINAL, VAR=cnt_borr_ADJ, GROUP=GROUP1, N_BAR=10, TYPE_VAR=NUM);

DATA plot.GINI_KS_CORR_FIN_adjVar;
SET GINI_KS_CORR_FIN;
RUN;

