
/* STATISTICS FOR NUMERIC VARIABLES */
ODS SELECT NONE;
PROC MEANS DATA=&USED_DATASET. StackODSOutput N NMISS SUM MEAN MODE STD MIN P1 P5 P25 MEDIAN P75 P95 P99 MAX; 
VAR &NUM_VAR.;
CLASS GROUP2;
ODS OUTPUT summary=LongPctls_GROUP;
RUN;

PROC MEANS DATA=&USED_DATASET. StackODSOutput N NMISS SUM MEAN MODE STD MIN P1 P5 P25 MEDIAN P75 P95 P99 MAX; 
VAR &NUM_VAR.;
ODS OUTPUT summary=LongPctls;
RUN;
ODS SELECT ALL;

DATA LongPctls;
RETAIN GROUP;
SET LongPctls_GROUP LongPctls ;

GROUP = STRIP(PUT(GROUP2,8.));
IF GROUP = . THEN GROUP = 'ALL';

FORMAT MISS_PERCENTAGE PERCENT7.2;
MISS_PERCENTAGE = NMISS/(NMISS+N);

DROP NObs _control_ GROUP2;

RUN;

PROC SORT DATA=LongPctls OUT=LongPctls;
BY Variable GROUP;
RUN;

PROC SQL; DROP TABLE LongPctls_GROUP; QUIT;


/* OUTLIER PROPORTION */

%MACRO OUTLIER_PERC(DATA, VAR);

PROC SQL NOPRINT;

	SELECT COUNT(*) INTO :TOTAL_PERC TRIMMED FROM VARIABLELIST WHERE TYPE = "NUM";
	SELECT VARIABLE INTO :VAR1-:VAR&TOTAL_PERC. FROM VARIABLELIST WHERE TYPE = "NUM";

QUIT;

	%DO O = 1 %TO &TOTAL_PERC.;
	%PUT ------------ &O. OF &TOTAL_PERC.: &&VAR&O.;

			PROC UNIVARIATE DATA=&DATA. NOPRINT;
			  VAR &&VAR&O.;
			  OUTPUT PCTLPRE=P_ PCTLPTS= 25, 75 OUT=P25_P75;
			RUN;

			PROC SQL NOPRINT; SELECT P_25, P_75 INTO :P25, :P75 FROM P25_P75; QUIT;

			PROC SQL;
				CREATE TABLE TEMP AS
					SELECT 
						"&&VAR&O." AS VARIABLE
						, &P25.-(&P75.-&P25.)*1.5 AS L_BOARDER
						, &P75.+(&P75.-&P25.)*1.5 AS H_BOARDER
						, SUM(LOWER) AS L_OUTLIER
						, SUM(HIGHER) AS H_OUTLIER
						, SUM(LOWER)+SUM(HIGHER) AS OUTLIER
						, SUM(LOWER)/COUNT(LOWER) AS L_OUTLIER_PERC FORMAT PERCENT9.4
						, SUM(HIGHER)/COUNT(HIGHER) AS H_OUTLIER_PERC FORMAT PERCENT9.4
						, (SUM(LOWER)+SUM(HIGHER))/COUNT(LOWER) AS OUTLIER_PERC FORMAT PERCENT9.4
					FROM	(
						SELECT
							CASE WHEN &&VAR&O. < &P25.-(&P75.-&P25.)*1.5 THEN 1 ELSE 0 END AS LOWER
							, CASE WHEN &&VAR&O. > &P75.+(&P75.-&P25.)*1.5 THEN 1 ELSE 0 END AS HIGHER
						FROM &USED_DATASET.
							) hl;
			QUIT;

			DATA OUTLIER_PERC;
			SET OUTLIER_PERC TEMP;
				IF VARIABLE = '' THEN DELETE;
			RUN;

			PROC SQL; DROP TABLE TEMP, P25_P75; QUIT;

%END;

%MEND;

DATA OUTLIER_PERC;
LENGTH VARIABLE $ 50;
RUN;

%OUTLIER_PERC(DATA=&USED_DATASET.);
