
/* STATISTICS FOR NUMERIC VARIABLES */
ODS SELECT NONE;
PROC MEANS DATA=&USED_DATASET. StackODSOutput N NMISS SUM MEAN STD MIN P1 P5 P25 MEDIAN P75 P95 P99 MAX; 
VAR &NUM_VAR.;
CLASS DEFAULT_12M;
ODS OUTPUT summary=LongPctls_DEF;
RUN;

PROC MEANS DATA=&USED_DATASET. StackODSOutput N NMISS SUM MEAN STD MIN P1 P5 P25 MEDIAN P75 P95 P99 MAX; 
VAR &NUM_VAR.;
ODS OUTPUT summary=LongPctls;
RUN;
ODS SELECT ALL;

DATA LongPctls;
RETAIN CATEGORY;
SET LongPctls_DEF LongPctls ;

CATEGORY = STRIP(PUT(DEFAULT_12M,8.));
IF CATEGORY = . THEN CATEGORY = 'ALL';

FORMAT MISS_PERCENTAGE PERCENT7.2;
MISS_PERC = NMISS/(NMISS+N);

DROP NObs _control_ DEFAULT_12M;

RUN;

PROC SORT DATA=LongPctls OUT=LongPctls;
BY Variable CATEGORY;
RUN;

PROC SQL; DROP TABLE LongPctls_DEF; QUIT;

PROC SQL;

CREATE TABLE GINI_grouped AS
	SELECT 
		pctls.*
		, gini.min_GINI
		, gini.max_GINI
		, gini.AUC
	FROM LongPctls pctls
	LEFT JOIN 
		(SELECT 
			LABEL
			, MIN(gini.GINI) AS min_GINI
			, MAX(gini.GINI) AS max_GINI
			, MAX(gini.AUC)  AS AUC
		FROM GINI_fin gini
		GROUP BY LABEL) gini

	ON pctls.LABEL = gini.LABEL
	AND CATEGORY = 'ALL';

QUIT;

ODS GRAPHICS OFF;

proc options option=config;
run;