proc options option=config;
run;

proc contents data=&USED_DATASET._FINAL;
RUN;

DATA UNIQUE_VALUES_ALLVAR;
LENGTH TYPE $ 5 VARIABLE $ 50 VALUE $ 100;
RUN;

%UNIQUE_VALUES_ALLVAR(DATA=&USED_DATASET._FINAL, TYPE_VAR=CAT);
%UNIQUE_VALUES_ALLVAR(DATA=&USED_DATASET._FINAL, TYPE_VAR=IND);
%UNIQUE_VALUES_ALLVAR(DATA=&USED_DATASET._FINAL, TYPE_VAR=NUM);

DATA TED;
SET final.TEST_SAMPLE(OBS=10);
RUN;