DATA &USED_DATASET._FINAL;
SET final.&USED_DATASET._FINAL(RENAME=(SELECTED = SELECTED_50_50));
RUN;

PROC SORT DATA=&USED_DATASET._FINAL ;
BY DEFAULT_12M GROUP2;
RUN;

PROC SURVEYSELECT 
	DATA=&USED_DATASET._FINAL 
	OUT=&USED_DATASET._FINAL 
	SAMPRATE=.9
	OUTALL
    METHOD=SRS
    SEED=26020703;       /*SET SEED TO MAKE THIS EXAMPLE REPRODUCIBLE*/
    STRATA DEFAULT_12M GROUP2; /*SPECIFY VARIABLE TO USE FOR STRATIFICATION*/
RUN;

DATA final.&USED_DATASET._FINAL;
SET &USED_DATASET._FINAL;
RENAME SELECTED = SELECTED_90_10;
RUN;