PROC SORT DATA=&USED_DATASET._FINAL ;
BY DEFAULT_12M GROUP2;
RUN;

PROC SURVEYSELECT 
	DATA=&USED_DATASET._FINAL 
	OUT=&USED_DATASET._FINAL 
	SAMPRATE=.7 
	OUTALL
    METHOD=SRS
    SEED=26020703;       /*SET SEED TO MAKE THIS EXAMPLE REPRODUCIBLE*/
    STRATA DEFAULT_12M GROUP2; /*SPECIFY VARIABLE TO USE FOR STRATIFICATION*/
RUN;

DATA final.&USED_DATASET._FINAL;
SET &USED_DATASET._FINAL;
RUN;